/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    EchartBase: typeof import('./src/components/global/EchartBase.vue')['default']
    EchartDrag: typeof import('./src/components/global/Echart-Drag.vue')['default']
    Logo: typeof import('./src/components/global/Logo.vue')['default']
    Picture: typeof import('./src/components/global/Picture.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SvgIcon: typeof import('./src/components/global/SvgIcon.vue')['default']
    UpLoad: typeof import('./src/components/global/UpLoad.vue')['default']
  }
}
